import Head from "next/head";
import Navbar from "../../components/Navbar";
import Main from "../../components/Main";
import About from "../../components/About";
import Skills from "../../components/Skills";
import Projects from "../../components/Projects";
import Certificate from "../../components/Certificate";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Songphon&apos;s Web Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Certificate />
    </div>
  );
}
